package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.domain.DicValue;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sun Jun 12 13:37:43 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sun Jun 12 13:37:43 CST 2022
     */
    int insert(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sun Jun 12 13:37:43 CST 2022
     */
    int insertSelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sun Jun 12 13:37:43 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sun Jun 12 13:37:43 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sun Jun 12 13:37:43 CST 2022
     */
    int updateByPrimaryKey(DicValue row);

    /**
     * 根据字典类型查询字典值列表
     * @param typeCode
     * @return
     */
    List<DicValue> selectDicByTypeCode(String typeCode);
}