package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.Activity;
import org.apache.ibatis.annotations.Param;
import org.springframework.jmx.export.annotation.ManagedOperationParameter;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ActivityMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbg.generated Sun May 29 15:57:44 CST 2022
     */
    int insert(Activity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbg.generated Sun May 29 15:57:44 CST 2022
     */
    int insertSelective(Activity row);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbg.generated Sun May 29 15:57:44 CST 2022
     */
    int updateByPrimaryKeySelective(Activity row);

    /**
     * 分页查询所有活动
     */
    List<Activity> queryAllActivityForPage();
    /**
     * 根据条件分页查询
     */
    List<Activity> queryAllByConditionsForPage(Map<String,Object> map);
    /**
     * 根据条件分页查询总条数
     */
    int querytotalCountByConditionsForPage(Map<String,Object> map);
    /**
     * 删除选中数据
     */
    int deleteByPrimaryKey(@Param("ids") String[] ids);
    /**根据id查询活动*/
    Activity selectByPrimaryKey(@Param("id") String id);
    /**
     * 更新活动
     */
    int updateByPrimaryKey(Activity row);

    /**
     *根据线索id查询市场活动
     * @param ClueId
     * @return
     */
    List<Activity> queryActivityByClueId(String ClueId);
    /**
     *根据线索id以及市场活动名字查询市场活动
     * @param
     * @return
     */
    List<Activity> queryActivityByActivityName(Map<String,Object> map);
    List<Activity> queryActivityForConvertByNameClueId(Map<String,Object> map);
}