package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.Activity;
import com.bjpowernode.crm.workbench.domain.ClueActivityRelation;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ClueActivityRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbg.generated Tue Jun 14 11:30:09 CST 2022
     */
    int deleteByPrimaryKey(String id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbg.generated Tue Jun 14 11:30:09 CST 2022
     */
    int insertSelective(ClueActivityRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbg.generated Tue Jun 14 11:30:09 CST 2022
     */
    ClueActivityRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbg.generated Tue Jun 14 11:30:09 CST 2022
     */
    int updateByPrimaryKeySelective(ClueActivityRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbg.generated Tue Jun 14 11:30:09 CST 2022
     */
    int updateByPrimaryKey(ClueActivityRelation row);
    /**
     *根据clueid和activityid创建关系
     */
    int insert(ClueActivityRelation row);
    /*
    根据clueid和activityid删除关系
     */
    int deleteByClueIdAndActivityId(Map<String,Object> map);
      /*
    根据clueid和activityid查找关系
     */
     String queryRelationByClueIdAndActivityId(Map<String,Object> map);
    /*
    根据clueid删除关系
    */
    int deleteByClueId(String clueId);
        /*
    根据clueid查询关系
    */
    String[] queryRelationByClueId(String clueId);
}