package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.Activity;
import com.bjpowernode.crm.workbench.domain.Customer;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbg.generated Fri Jun 17 16:00:21 CST 2022
     */
    int deleteByPrimaryKey(String id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbg.generated Fri Jun 17 16:00:21 CST 2022
     */
    int insertSelective(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbg.generated Fri Jun 17 16:00:21 CST 2022
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbg.generated Fri Jun 17 16:00:21 CST 2022
     */
    int updateByPrimaryKeySelective(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbg.generated Fri Jun 17 16:00:21 CST 2022
     */
    int updateByPrimaryKey(Customer row);
    /**
     * 添加客户
     */
    int insert(Customer row);
    /**
     * 根据条件分页查询
     */
    List<Customer> queryAllByConditionsForPage(Map<String,Object> map);
    /**
     * 根据条件查询总条数
     */
    int queryCountByConditionsForPage(Map<String,Object> map);
    /**
     * 根据名称查询客户名称
     */
   List<String> queryCustomNameByName(String name);
    /**
     * 根据名称精确查询客户
     */
    Customer queryCustomerByName(String name);

}